export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e4e2df',
        'outline-variant': '#c4c7c7',
        'tertiary-fixed': '#f3dfce',
        'tertiary-fixed-dim': '#d6c3b3',
        'on-primary-container': '#949393',
        background: '#fbf9f6',
        'on-primary-fixed': '#1b1c1c',
        'tertiary-container': '#352a1f',
        secondary: '#5e5e5e',
        primary: '#171818',
        'on-background': '#1b1c1a',
        error: '#ba1a1a',
        tertiary: '#1f160c',
        'surface-bright': '#fbf9f6',
        'surface-tint': '#5f5e5e',
        'on-tertiary': '#ffffff',
        'on-surface': '#1b1c1a',
        'secondary-fixed': '#e3e2e2',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#30312f',
        'primary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c7c6c6',
        'on-tertiary-fixed-variant': '#514538',
        'inverse-primary': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed-variant': '#474747',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-container': '#2c2c2c',
        'surface-container-high': '#eae8e5',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'secondary-container': '#e3e2e2',
        outline: '#747878',
        'on-tertiary-container': '#a19181',
        'surface-container-highest': '#e4e2df',
        'on-surface-variant': '#444748',
        'on-secondary-fixed-variant': '#464747',
        'inverse-on-surface': '#f2f0ed',
        'on-tertiary-fixed': '#231a0f',
        surface: '#fbf9f6',
        'surface-dim': '#dbdad7',
        'on-secondary-container': '#646464',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: { gutter: '24px', 'container-max': '1200px', 'margin-desktop': '48px', unit: '8px', 'section-gap': '64px', 'margin-mobile': '20px' },
      fontFamily: {
        'headline-lg': ['Manrope'], 'label-sm': ['Plus Jakarta Sans'], 'body-md': ['Plus Jakarta Sans'], 'body-lg': ['Plus Jakarta Sans'], 'label-caps': ['Manrope'], 'headline-md': ['Manrope'], 'headline-lg-mobile': ['Manrope'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
